language: python
os: osx
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
# command to install dependencies
install:
  - pip install -q tox-travis
  - pip install -q pytest
  - pip install -q pytest-cov
  - pip install -r requirements.txt
  # For testing cleanlab.models
  - pip install -qq torch torchvision
  - pip install -q -e .
  # - pip install git+https://github.com/cgnorthcutt/cleanlab.git
# command to run tests
script:
  - tox 
  - bash <(curl -s https://codecov.io/bash) -t c1817983-8176-4535-b31d-9fa9d649438a